name: core-action

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-norme:
    uses: ./.github/workflows/norm.yml

  ckeck-basic:
    need [ check-norme ]
    uses: ./.github/workflows/check.yml
    with:
      executables: "ai"
