name: Pull Request Notification
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  notification:
    runs-on: ubuntu-latest
    env:
      SIZE: 0
      SIZE_O: 0
      SIZE_MAX: "non definis"
      SIZE_MAX_O: 30MB
    steps:
    - uses: actions/checkout@v3
    - name: Get Repo Size
      run: |
        repo_size=$(git ls-tree -r --name-only main | xargs du -c --exclude=".git" | tail -n 1 | awk '{print $1}')
        repo_size_commande=$(git ls-tree -r --name-only main | xargs du -h -c --exclude=".git" | tail -n 1 | awk '{print $1}')
        echo "SIZE=$repo_size" >> $GITHUB_ENV
        echo "SIZE_O=$repo_size_commande" >> $GITHUB_ENV

    - name: Send notification
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pullRequest.number,
            body: '<table><thead><tr><th>Size</th><th>Size Max</th></tr></thead><tr><td>${{ env.SIZE_O }}</td><td>${{ env.SIZE_MAX_O }}</td></tr><tr><td>${{ env.SIZE }}</td><td>${{ env.SIZE_MAX }}</td></tr></table>'
          });

